name: Update Data

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 */4 * * *"  # Runs every 5 minutes
  workflow_dispatch:  
  
jobs:
  update_data:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_T }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_T }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_T }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_T }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_T }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_T }}
      FRED_API: ${{ secrets.FRED_API_T }}
      GCLOUD_BUCKET_NAME: ${{ secrets.GCLOUD_BUCKET_NAME }}
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
    
    steps:
      - name: Debug GitHub Event
        run: echo "${{ github.event_name }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json

      - name: Run Python script to upload FRED data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API }}
          GCP_BUCKET_NAME: ${{ secrets.GCLOUD_BUCKET_NAME }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        run: python scripts/load_raw_data.py
